--Toàn bộ thông tin của tất cả các lớp trong trường.
SELECT *
from LOP;

--Những học sinh chưa có tên của phụ huynh.
select MaHS, HotenHS
from HOCSINH
where HoTenPH IS NULL;

--Những lớp chưa có giáo viên chủ nhiệm
select MaLop
from LOP
where MaGVCN IS NULL;

select MaHS, DiaChi
from HOCSINH
where GioiTinh = 'Nu' AND DiaChi LIKE '%Duong%';

SELECT *
FROM HOCSINH
WHERE (GioiTinh = 'Nam' AND DiaChi LIKE '%X%')
   OR (GioiTinh = 'Nu' AND DiaChi LIKE '%Y%');

SELECT *
FROM HOCSINH
WHERE (GioiTinh = 'Nam' AND HoTenPH IS NULL)
   AND (GioiTinh = 'Nu' AND MaLop IS NULL);


SELECT *
FROM HOCSINH
WHERE GioiTinh = 'Nam' AND (HoTenPH IS NULL AND  MaLop IS NULL);

SELECT DISTINCT MaMH
FROM KETQUAHOCTAP
WHERE HocKy = 2;

select MaHS, HoTenHS, GioiTinh, DiaChi, MaLop
from HOCSINH
where HoTenHS like 'Nguyen%'

select MaHS, HoTenHS, GioiTinh, DiaChi, MaLop
from HOCSINH
where HoTenHS like '%No'

select MaHS, HoTenHS, GioiTinh, DiaChi, MaLop
from HOCSINH
where HoTenHS like '%Thi%'

select MaHS, HoTenHS, GioiTinh, DiaChi, MaLop
from HOCSINH
where HoTenHS like '_%Thi_%';

SELECT *
FROM HOCSINH
WHERE HoTenHS NOT LIKE 'Ng%';

SELECT DISTINCT MaMH
FROM PHUTRACHBOMON;

SELECT DISTINCT MaMH
FROM KETQUAHOCTAP;

SELECT DISTINCT MaGVCN
FROM LOP
WHERE MaGVCN IS NOT NULL;

SELECT * 
FROM HOCSINH
ORDER BY HoTenHS, DiaChi DESC ;

SELECT * 
FROM HOCSINH
ORDER BY HoTenHS DESC, DiaChi DESC, HoTenPH;

SELECT	HOCSINH.MaHS, HoTenHS, HocKy, MaMH, DiemThiGiuaKy, DiemThiCuoiKy
FROM HOCSINH
INNER JOIN KETQUAHOCTAP
ON HOCSINH.MaHS = KETQUAHOCTAP.MaHS;

SELECT MaGV, HoTenGV, MaLop, MaMH, HocKy 
FROM GIAOVIEN
INNER JOIN PHUTRACHBOMON
ON GIAOVIEN.MaGV = PHUTRACHBOMON.MaGVPT;

SELECT	HOCSINH.MaHS, HoTenHS, HocKy, MONHOC.MaMH, TenMH, DiemThiGiuaKy, DiemThiCuoiKy 
FROM HOCSINH
INNER JOIN KETQUAHOCTAP ON HOCSINH.MaHS = KETQUAHOCTAP.MaHS
INNER JOIN MONHOC ON KETQUAHOCTAP.MaMH = MONHOC.MaMH;

SELECT DISTINCT HOCSINH.MaHS, HoTenHS, PHUTRACHBOMON.HocKy, MONHOC.MaMH, TenMH, DiemThiGiuaKy, DiemThiCuoiKy, PHUTRACHBOMON.MaLop, PHUTRACHBOMON.MaGVPT, HoTenGV 
FROM HOCSINH
INNER JOIN KETQUAHOCTAP ON HOCSINH.MaHS = KETQUAHOCTAP.MaHS
INNER JOIN MONHOC ON KETQUAHOCTAP.MaMH = MONHOC.MaMH
INNER JOIN PHUTRACHBOMON ON MONHOC.MaMH = PHUTRACHBOMON.MaMH
INNER JOIN GIAOVIEN ON PHUTRACHBOMON.MaGVPT = GIAOVIEN.MaGV

SELECT
    HS.MaHS, HS.HoTenHS, PB.HocKy, MH.MaMH, MH.TenMH,
    KQ.DiemThiGiuaKy, KQ.DiemThiCuoiKy, PB.MaLop, PB.MaGVPT, GV.HoTenGV
FROM HOCSINH HS
INNER JOIN KETQUAHOCTAP KQ ON HS.MaHS = KQ.MaHS
INNER JOIN MONHOC MH ON KQ.MaMH = MH.MaMH
INNER JOIN PHUTRACHBOMON PB ON MH.MaMH = PB.MaMH AND PB.MaLop = HS.MaLop
INNER JOIN GIAOVIEN GV ON PB.MaGVPT = GV.MaGV;

SELECT
    HS.MaHS, HS.HoTenHS, L.MaLop, L.MaGVCN, GV.HoTenGV, PB.HocKy, MH.MaMH, MH.TenMH,
    KQ.DiemThiGiuaKy, KQ.DiemThiCuoiKy, PB.MaLop, PB.MaGVPT, GV.HoTenGV
FROM HOCSINH HS
INNER JOIN KETQUAHOCTAP KQ ON HS.MaHS = KQ.MaHS
INNER JOIN MONHOC MH ON KQ.MaMH = MH.MaMH
INNER JOIN PHUTRACHBOMON PB ON MH.MaMH = PB.MaMH AND PB.MaLop = HS.MaLop
INNER JOIN GIAOVIEN GV ON PB.MaGVPT = GV.MaGV
INNER JOIN LOP L ON HS.MaLop = L.MaLop AND GV.MaGV = L.MaGVCN AND PB.MaLop = L.MaLop;

SELECT
    HS.MaHS, HS.HoTenHS, L.MaLop, L.MaGVCN, GVCN.HoTenGV AS HoTenGVCN,
    PB.HocKy, MH.MaMH, MH.TenMH, KQ.DiemThiGiuaKy, KQ.DiemThiCuoiKy,
    GVPT.MaGV AS MaGVPT, GVPT.HoTenGV AS HoTenGVPT
FROM HOCSINH HS
JOIN KETQUAHOCTAP KQ ON HS.MaHS = KQ.MaHS
JOIN MONHOC MH ON KQ.MaMH = MH.MaMH
JOIN LOP L ON HS.MaLop = L.MaLop
JOIN PHUTRACHBOMON PB ON MH.MaMH = PB.MaMH AND L.MaLop = PB.MaLop AND KQ.HocKy = PB.HocKy
JOIN GIAOVIEN GVCN ON L.MaGVCN = GVCN.MaGV
JOIN GIAOVIEN GVPT ON PB.MaGVPT = GVPT.MaGV;

SELECT
    HS.MaHS, HS.HoTenHS, L.MaLop, L.MaGVCN, GVCN.HoTenGV AS HoTenGVCN,
    PB.HocKy, MH.MaMH, MH.TenMH, KQ.DiemThiGiuaKy, KQ.DiemThiCuoiKy,
    GVPT.MaGV AS MaGVPT, GVPT.HoTenGV AS HoTenGVPT
FROM HOCSINH HS
JOIN KETQUAHOCTAP KQ ON HS.MaHS = KQ.MaHS
JOIN MONHOC MH ON KQ.MaMH = MH.MaMH
JOIN LOP L ON HS.MaLop = L.MaLop
JOIN PHUTRACHBOMON PB ON MH.MaMH = PB.MaMH AND L.MaLop = PB.MaLop AND KQ.HocKy = PB.HocKy
JOIN GIAOVIEN GVCN ON L.MaGVCN = GVCN.MaGV
JOIN GIAOVIEN GVPT ON PB.MaGVPT = GVPT.MaGV
WHERE HS.GioiTinh = 'Nu' AND (KQ.DiemThiGiuaKy >= 9 OR KQ.DiemThiCuoiKy >= 9) ;

SELECT
    HS.MaHS, HS.HoTenHS, KQ.HocKy, MH.MaMH, MH.TenMH,
    KQ.DiemThiGiuaKy, KQ.DiemThiCuoiKy, L.MaLop, GVCN.MaGV , GVCN.HoTenGV 
FROM HOCSINH HS
JOIN KETQUAHOCTAP KQ ON HS.MaHS = KQ.MaHS
JOIN MONHOC MH ON KQ.MaMH = MH.MaMH
JOIN LOP L ON HS.MaLop = L.MaLop
JOIN PHUTRACHBOMON PB ON MH.MaMH = PB.MaMH AND L.MaLop= PB.MaLop AND KQ.HocKy = PB.Hocky
JOIN GIAOVIEN GVCN ON L.MaGVCN = GVCN.MaGV
JOIN GIAOVIEN GVPT ON PB.MaGVPT = GVPT.MaGV
WHERE GVCN.MaGV = PB.MaGVPT;

SELECT MaMH, MaLop, HocKy 
FROM KETQUAHOCTAP KQ
JOIN HOCSINH HS ON KQ.MaHS = HS.MaHS
WHERE YEAR(KQ.NgayGioThiCuoiKy) = 2023 AND MONTH(KQ.NgayGioThiCuoiKy) = 8;

SELECT MaMH, MaLop, HocKy
FROM KETQUAHOCTAP KQ
JOIN HOCSINH HS ON KQ.MaHS = HS.MaHS
WHERE KQ.NgayGioThiCuoiKy < '08-20-2019';

SELECT DISTINCT MH.MaMH, L.MaLop, KQ.HocKy
FROM KETQUAHOCTAP KQ
JOIN MONHOC MH ON KQ.MaMH = MH.MaMH
JOIN HOCSINH HS ON KQ.MaHS = HS.MaHS
JOIN LOP L ON HS.MaLop = L.MaLop
WHERE KQ.NgayGioThiCuoiKy > '2019-08-20' AND KQ.NgayGioThiCuoiKy <= DATEADD(day, 21, '2019-08-20');

SELECT DISTINCT MaMH, MaLop, HocKy
FROM KETQUAHOCTAP KQ
JOIN HOCSINH HS ON KQ.MaHS = HS.MaHS
WHERE KQ.NgayGioThiCuoiKy > '2023-12-10' AND KQ.NgayGioThiCuoiKy <= DATEADD(day, 21, '2023-12-10');

SELECT DISTINCT MaMH, MaLop, HocKy
FROM KETQUAHOCTAP KQ
JOIN HOCSINH HS ON KQ.MaHS = HS.MaHS
WHERE KQ.NgayGioThiCuoiKy < '2023-12-20' AND KQ.NgayGioThiCuoiKy >= DATEADD(day, 7, '2023-12-10');

SELECT DISTINCT MaMH, MaLop, HocKy
FROM KETQUAHOCTAP KQ
JOIN HOCSINH HS ON KQ.MaHS = HS.MaHS
WHERE KQ.NgayGioThiCuoiKy BETWEEN '2023-12-10 10:00:00' AND '2023-12-20';

SELECT DISTINCT DiaChi
FROM  HOCSINH;

SELECT DiaCHi
FROM  HOCSINH
Group by DiaChi;

SELECT HoTenHS, GioiTinh 
FROM HOCSINH
GROUP BY HoTenHS, GioiTinh ;

SELECT HoTenHS
FROM HOCSINH
GROUP BY HoTenHS, GioiTinh;

SELECT MH.MaMH, MH.TenMH, KQ.DiemThiCuoiKy
FROM MONHOC MH
JOIN KETQUAHOCTAP KQ ON MH.MaMH = KQ.MaMH
WHERE KQ.DiemThiCuoiKy IS NOT NULL
GROUP BY MH.MaMH, MH.TenMH, KQ.DiemThiCuoiKy

SELECT DISTINCT GV.MaGV, GV.HoTenGV
FROM GIAOVIEN GV
JOIN PHUTRACHBOMON PB ON GV.MaGV = PB.MaGVPT
GROUP BY GV.MaGV, GV.HoTenGV;

SELECT COUNT(*) AS SoLuongHSNam
FROM HOCSINH
WHERE GioiTinh = 'Nam';

SELECT COUNT(*) AS SoLuong
FROM HOCSINH
JOIN LOP ON HOCSINH.MaLop = LOP.MaLop
WHERE LOP.TenLop = 'Lop 1/1' AND NamHoc = '2019-2020';

SELECT MaGVPT, COUNT(DISTINCT MaLop) AS SoLopPhuTrach
FROM PHUTRACHBOMON 
GROUP BY MaGVPT;

SELECT *
FROM GIAOVIEN
WHERE MaGV NOT IN ( SELECT MaGVPT FROM PHUTRACHBOMON WHERE MaGVPT IS NOT NULL);

SELECT GV.MaGV
FROM GIAOVIEN GV  WHERE  NOT EXISTS 
(SELECT  1
FROM  PHUTRACHBOMON PB
where PB.MaGVPT = GV.MaGV);

SELECT * 
FROM GIAOVIEN
WHERE MaGV NOT IN (SELECT MaGVCN FROM LOP);

SELECT MaGV, HoTenGV
FROM GIAOVIEN
WHERE MaGV NOT IN (SELECT MaGVCN FROM LOP WHERE MaGVCN IS NOT NULL);

SELECT MH.MaMH
FROM MONHOC MH 
WHERE NOT EXISTS (SELECT 1 FROM KETQUAHOCTAP KQ WHERE MH.MaMH = KQ.MaMH);

(SELECT HoTenHS as HOTEN
FROM HOCSINH )
UNION 
(SELECT HoTenGV as HOTEN
FROM GIAOVIEN);

(SELECT HoTenHS as HOTEN, 'Hoc sinh' AS [NGHE NGHIEP]
FROM HOCSINH )
UNION ALL
(SELECT HoTenGV as HOTEN,'Giao vien' AS [NGHE NGHIEP]
FROM GIAOVIEN);

SELECT HS.MaHS, HS.HoTenHS
FROM HOCSINH HS
JOIN LOP L ON HS.MaLop = L.MaLop
WHERE L.NamHoc = '2019-2020'

UNION

SELECT HS.MaHS, HS.HoTenHS
FROM HOCSINH HS
WHERE HS.MaHS NOT IN (
    SELECT KQ.MaHS
    FROM KETQUAHOCTAP KQ
    WHERE KQ.MaMH IN ('TOAN', 'TV')
);

(SELECT MONTH(NgayGioThiCuoiKy) AS Thang, COUNT(*) AS LuotThiToan
 FROM KETQUAHOCTAP
 WHERE YEAR(NgayGioThiCuoiKy) = 2023 AND MaMH = 'Toan'
 GROUP BY MONTH(NgayGioThiCuoiKy)
 HAVING COUNT(*) >= 3)
UNION 
(SELECT MONTH(NgayGioThiCuoiKy) AS Thang, COUNT(*) AS LuotThiTiengViet
 FROM KETQUAHOCTAP
 WHERE YEAR(NgayGioThiCuoiKy) = 2023 AND MaMH = 'Tieng Viet'
 GROUP BY MONTH(NgayGioThiCuoiKy))


WITH BangThang AS (
    SELECT 1 AS Thang UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL
    SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL
    SELECT 9 UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12
), ThongKe AS
		(SELECT MONTH(NgayGioThiCuoiKy) AS Thang,
			CASE WHEN MaMH = 'TOAN' THEN COUNT(*) ELSE 0 END AS LuotThiToan,
			CASE WHEN MaMH = 'TV' THEN COUNT(*) ELSE 0 END AS LuotThiTiengViet
		FROM KETQUAHOCTAP
		WHERE YEAR(NgayGioThiCuoiKy) = 2023 AND MaMH IN ('TOAN', 'TV')
		GROUP BY MONTH(NgayGioThiCuoiKy), MaMH
		HAVING (MaMH = 'TOAN' AND COUNT(*) >= 3) OR MaMH = 'TV')
SELECT BT.Thang, ISNULL(LuotThiToan, 0) AS LuotThiToan, ISNULL(LuotThiTiengViet, 0) AS LuotThiTiengViet
FROM BangThang BT
LEFT JOIN ThongKe ON BT.Thang = ThongKe.Thang

SELECT HS.MaHS, HoTenHS, HocKy, KQ.MaMH, TenMH, DiemThiGiuaKy, DiemThiCuoiKy
FROM HOCSINH HS
LEFT JOIN KETQUAHOCTAP KQ ON HS.MaHS = KQ.MaHS
LEFT JOIN MONHOC MH ON KQ.MaMH = MH.MaMH;

SELECT HS.MaHS, HoTenHS, HS.MaLop, TenLop, MaGVCN, HoTenGV 
FROM HOCSINH HS
LEFT JOIN LOP ON HS.MaLop = LOP.MaLop
LEFT JOIN GIAOVIEN GV ON LOP.MaGVCN = GV.MaGV;

SELECT MaGV, HoTenGV, LOP.MaLop, TenLop, PB.MaMH, HocKy, TenMH
FROM PHUTRACHBOMON PB
RIGHT JOIN GIAOVIEN GV ON PB.MaGVPT = GV.MaGV
LEFT JOIN LOP ON PB.MaLop = LOP.MaLop
LEFT JOIN MONHOC MH ON PB.MaMH = MH.MaMH;

SELECT DISTINCT MH.MaMH, TenMH, MaGV, HoTenGV
FROM MONHOC MH
FULL JOIN PHUTRACHBOMON PB ON MH.MaMH = PB.MaMH
FULL JOIN GIAOVIEN GV ON PB.MaGVPT = GV.MaGV;

(SELECT HS.MaHS, HoTenHS
FROM HOCSINH HS
JOIN KETQUAHOCTAP KQ ON HS.MaHS = KQ.MaHS
WHERE MaMH = 'TOAN' AND HocKy = 1)
INTERSECT
(SELECT HS.MaHS, HoTenHS
FROM HOCSINH HS
JOIN KETQUAHOCTAP KQ ON HS.MaHS = KQ.MaHS
WHERE MaMH = 'AN' AND HocKy = 2);

(SELECT MH.MaMH, MH.TenMH
FROM MONHOC MH
JOIN KETQUAHOCTAP KQ ON MH.MaMH = KQ.MaMH
GROUP BY MH.MaMH, MH.TenMH
HAVING COUNT(DISTINCT KQ.MaHS) >= 5)
INTERSECT
(SELECT MH.MaMH, MH.TenMH
FROM MONHOC MH
JOIN PHUTRACHBOMON PB ON MH.MaMH = PB.MaMH
GROUP BY MH.MaMH, MH.TenMH
HAVING COUNT(DISTINCT PB.MaGVPT) >= 2)

(SELECT MaGV, HoTenGV
FROM GIAOVIEN GV
JOIN LOP L ON GV.MaGV = L.MaGVCN)
EXCEPT
(SELECT MaGV, HoTenGV
FROM GIAOVIEN GV
JOIN PHUTRACHBOMON PB ON GV.MaGV = PB.MaGVPT
WHERE MaMH = 'AN');

(SELECT HS.MaHS, HoTenHS
FROM HOCSINH HS
JOIN KETQUAHOCTAP KQ ON HS.MaHS = KQ.MaHS
WHERE MaMH = 'TOAN' AND HocKy = 1)
EXCEPT
(SELECT HS.MaHS, HoTenHS
FROM HOCSINH HS
JOIN KETQUAHOCTAP KQ ON HS.MaHS = KQ.MaHS
WHERE MaMH = 'AN' AND HocKy = 2);

(SELECT MH.MaMH, MH.TenMH
FROM MONHOC MH
JOIN KETQUAHOCTAP KQ ON MH.MaMH = KQ.MaMH
GROUP BY MH.MaMH, MH.TenMH
HAVING COUNT(DISTINCT KQ.MaHS) >= 5)
INTERSECT
(SELECT MH.MaMH, MH.TenMH
FROM MONHOC MH
JOIN PHUTRACHBOMON PB ON MH.MaMH = PB.MaMH
GROUP BY MH.MaMH, MH.TenMH
HAVING COUNT(DISTINCT PB.MaGVPT) = 2)
